services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tiktok_clone
      POSTGRES_USER: postgres
    ports:
        - "5432:5432"
    volumes: 
        - db:/var/lib/postgresql
    networks:
        - tiktok_network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d tiktok_clone"]
        interval: 5s
        timeout: 5s
        retries: 10
  api:
    build: 
      dockerfile: .dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitMQ
      - ConnectionStrings__DefaultConnection=Host=db;password=mypassword;username=postgres;database=tiktok_clone
      - AWS__S3__ServiceUrl=http://localstack:4566
      - AWS__S3__CdnScheme=http
      - AWS__S3__CdnDomain=localhost:4566
    volumes:
      - api_logs:/app/logs
    networks:
      - tiktok_network
    depends_on:
      db:
        condition: service_healthy
      rabbitMQ:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped
  video_processor:
    build: 
      dockerfile: VideoProcessor/.dockerfile
    container_name: video_processor
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitMQ
      - AWS__S3__ServiceUrl=http://localstack:4566
    networks: 
      - tiktok_network
    depends_on:
      db:
        condition: service_healthy
      rabbitMQ:
        condition: service_healthy
  rabbitMQ:
    container_name: "rabbitMQ"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tiktok_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  localstack:
    image: localstack/localstack:3.8.0
    ports:
      - "4566:4566"
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
    networks:
      - tiktok_network
    healthcheck:
      test: ["CMD","awslocal","s3","ls"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

networks:
  tiktok_network:
    name: "tiktok_network"

volumes:
  db:
    driver: local
    name: "db"
  rabbitmq_data:
    driver: local
    name: "rabbitmq_data"
  api_logs:
    driver: local
    name: "api_logs"
  localstack_data:
    driver: local
    name: "localstack_data"
