# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy all .csproj files and restore
COPY ["Tiktok_Clone/Tiktok_Clone.csproj", "Tiktok_Clone/"]

RUN dotnet restore "Tiktok_Clone/Tiktok_Clone.csproj"

# Copy everything and publish
COPY . .
WORKDIR /src/Tiktok_Clone
RUN dotnet publish "Tiktok_Clone.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy published output
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Tiktok_Clone.dll"]