<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <Compile Remove="Validators\**"/>
        <EmbeddedResource Remove="Validators\**"/>
        <None Remove="Validators\**"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Contracts\Contracts.csproj"/>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Riok.Mapperly"/>
        <PackageReference Include="Nanoid" />

    </ItemGroup>

</Project>
