<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="DotNetEnv"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>

        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Serilog.Settings.Configuration"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj"/>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj"/>
        <ProjectReference Include="..\Persistence\Persistence.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update=".env">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update=".env_example">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </None>
        <None Update="Templates\ResetPassword.html">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\ConfirmEmail.html">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\master.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\thumbnail.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\playlist.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\seg_000.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\seg_001.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\seg_002.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\seg_003.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggVideo\1080\seg_004.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\master.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\thumbnail.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\playlist.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\seg_000.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\seg_001.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\seg_002.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\seg_003.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\ThraggEdit\1080\seg_004.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\1080\playlist.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\1080\seg_000.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\1080\seg_001.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\1080\seg_002.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\master.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\China\thumbnail.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\playlist.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_000.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_001.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_002.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_003.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_004.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_005.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_006.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_007.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_008.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_009.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_010.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_011.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_012.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_013.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\1080\seg_014.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\master.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\RickRoll\thumbnail.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\playlist.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_000.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_001.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_002.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_003.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_004.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_005.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_006.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_007.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_008.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_009.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_010.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_011.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_012.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_013.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\1080\seg_014.ts">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\master.m3u8">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="SeedVideos\WetFart\thumbnail.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="SeedVideos\" />
    </ItemGroup>

</Project>
